resources:
- name: pull-request
  webhook_token: EuTxbtqjFL7ozQrTehmE
  type: pull-request
  source:
    access_token: ((github-access-token))
    repository: TeliaSoneraNorge/telia-terraform-modules

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: itsdalmo/github-pr-resource

jobs:
- name: test
  plan:
  - get: pull-request
    trigger: true
    version: every
  - put: pull-request
    params:
      path: pull-request
      context: please-ignore
      status: pending
  - task: unit-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine/git
          tag: latest
      run:
        path: /bin/sh
        args:
        - -xce
        - |
          cd pull-request
          git log --graph --all --color --pretty=format:"%x1b[31m%h%x09%x1b[32m%d%x1b[0m%x20%s" > log.txt
          cat log.txt
          cat .git/config
      inputs:
      - name: pull-request
  - put: pull-request
    params:
      path: pull-request
      context: please-ignore
      status: success
